services:
  # app:
  #   image: smart_system:2
  #   container_name: app_smart_system
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 8000:8000

  db_redis:
    image: redis:latest
    container_name: redis_smart_system
    # restart: always
    ports:
      - "6379:6379"

  db_postgres:
    image: postgres:13
    container_name: postgres_smart_system
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

    volumes:
      - pg-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm

volumes:
  pg-data:
